# This file is part of requests2jmx-via-bzt.
# https://github.com/belonesox/requests2jmx-via-bzt

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2018, Stas Fomin <stas-fomin@yandex.ru>

language: python

python:
    - "2.7"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
